### ISSUE TITLE
Images/Hyperlink in Cell

### ISSUE THREAD

**Issue by smit27589** [erfangc/ReactTable#23]
Need cells which can support hyperlinks or images.

**Comment by erfangc** [comment]
I can work on this - the idea is to allow for custom callbacks during cell creation - where the callback function must return a 'react component' (i.e. a <div />)

as a preliminary, let's add this functionality to cfg objects in `columnDefs` i.e.

```js
var colDefs = [
    { colTag: "...",
      cellTemplate: function(content) {
                                   return <div><a>I am a link</a></div>
                            }
]
```

**Comment by erfangc** [comment]
see commit b0a3cd2c29295a774a73458b191c26d954740cf6

this feature has been added. There is also a cell_template.html/js file under examples
