### ISSUE TITLE
Cell callback

### ISSUE THREAD

**Issue by smit27589** [erfangc/ReactTable#25]
Row callbacks work but we need to perform cell specific operations if the user clicks on a particular cell of the row like right click or double click on a cell which will work as a filter, etc..

**Comment by erfangc** [comment]
this was added in commit bda4550ba457875a3dc9ee8ced5e04c79076d8e7

onCellSelect

custom callback function that triggers when a cell in this column is clicked. this is bound to the row component, first argument to the callback is the cell content
