### ISSUE TITLE
Export to PDF or Excel

### ISSUE THREAD

**Issue by caguthrie** [erfangc/ReactTable#29]

**Comment by erfangc** [comment]
any idea how that might be done on the client side?

it wouldn't be too hard on the server side

**Comment by arjshiv** [comment]
Reasonably simple - Just use dynamic links with the 'download' attribute to trigger a download. This is not supported in IE (naturally) but it's possible to just provide a ustom callback that will make a call to the server side to do it in that case.

**Comment by caguthrie** [comment]
done 4d8331103a5daebf657f60d687fd516d25eaf9ea

Requires table2CSV.js dependency.  Right now you have to manually add it in your project.  Maybe we should just build this into the dist file?
