### ISSUE TITLE
Excel functionality does not work for large data

### ISSUE THREAD

**Issue by smit27589** [erfangc/ReactTable#34]
Tried exporting to excel for a dataset with 12000 rows and 12 columns.
It causes chrome to crash.

**Comment by caguthrie** [comment]
This appears to be a limitation of base64 data loaded over http.  We need to explore alternatives to exporting large datasets

**Comment by caguthrie** [comment]
Fixed in 1b9fa8e22389cc535f8de95c001f88405285dba6
