### ISSUE TITLE
The "+" button at the end of the table is broken

### ISSUE THREAD

**Issue by erfangc** [erfangc/ReactTable#47]
In the master version the plus button is now somehow either overlapping the last header cell or exhibiting other behaviors. this is likely the result of the new grand total column at the bottom of the table

**Comment by erfangc** [comment]
@wenjiechen have you had a chance to get `master` to work again?

**Comment by erfangc** [comment]
Team, if we cannot fix `master` I will have to rebase master to v3.0.2. That will cause the changes to master since that commit to be lost. currently there are many bugs in `master` even the pagination appears to be broken.

Should we start over from v3.0.2? reorganize our efforts and lets more closely examine the code this time?

**Comment by wenjiechen** [comment]
fixed the '+' button. can you try my version ? 
https://github.com/wenjiechen/ReactTable
