### ISSUE TITLE
Slowness of the master

### ISSUE THREAD

**Issue by erfangc** [erfangc/ReactTable#48]
the current table seems significantly slower than before, as discussed with @wenjiechen this appears to be caused by `adjustHeaders()`

we either have to reimplement the header and grand total footer using a method that does not rely on `adjustHeader()` OR we have to investigate why `adjustHeader()` is suddenly slowing the widget down significantly more than before

**Comment by erfangc** [comment]
hey @wenjiechen you mentioned this is b/c adjustHeader is being called repeatedly right? 

`adjustHeader()` have existed before the last few commits by you, something in the new code must have triggered to to run much more frequently now. Shall we take a look?

**Comment by wenjiechen** [comment]
yes, when I add an grand total footer, the adjustHeaders() become slower. I think we need a way to get rid of adjustHeaders(), or don't reply on it too much.

**Comment by wenjiechen** [comment]
one way is use  <footer> and <th> replace <dv > of grand total and headers, and use jquery to fix header and footer. in this way we don't calculate column's width for footers and headers

**Comment by erfangc** [comment]
what if we pre-calculate column width and create a ```html <table />```` on top of / bottom of the main data table?

**Comment by erfangc** [comment]
ps. your last comment isn't formatted correctly

**Comment by wenjiechen** [comment]
pre-calculate is a good idea.
